MovieShop.MVC/Controllers/CastController.cs
using MovieShop.Entities;
using MovieShop.MVC.ViewModel;
using MovieShop.Services;
using MovieShop.Data;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    [RoutePrefix("cast")]
    public class CastController : Controller
    {
        private CastService _castService;

        public CastController()
        {
            _castService = new CastService();
        }

        // GET: Cast
        [HttpGet]
        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            var cast = _castService.GetCastDetails(id);
            var castDetailsViewModel = new CastDetailsViewModel();
            castDetailsViewModel.Id = cast.Id;
            castDetailsViewModel.Name = cast.Name;
            castDetailsViewModel.ProfilePath = cast.ProfilePath;
            castDetailsViewModel.TmdbUrl = cast.TmdbUrl;
            castDetailsViewModel.Gender = cast.Gender;
            castDetailsViewModel.Movies = new List<MovieViewModel>();

            foreach (var movie in cast.MovieCasts)
            {
                castDetailsViewModel.Movies.Add(new MovieViewModel() {Id=movie.MovieId,Title = movie.Movie.Title });

            }
            return View(castDetailsViewModel);

        }
        [HttpGet]
        [Route("Index")]//localhost/Cast/Index
        public ActionResult Index()
        {
            var casts = _castService.GetAllCast();
            return View(casts);
        }
        [HttpGet]
        public ActionResult Create()
        {
            //Cast db = new Cast();
            //List<Cast> listOfCast = 
            return View();
        }

        //Model Binding:pass by name or object in the params
        //
        [HttpPost]
        public ActionResult Create(Cast cast)
        {
            _castService.CreateCast(cast);
            ////save to database
            //using (var x = new DbContext)
            MovieShopDbContext db = new MovieShopDbContext();
            db.Casts.Add(new Cast { Name = cast.Name, Gender = cast.Gender, TmdbUrl = cast.TmdbUrl, ProfilePath = cast.ProfilePath });
            db.SaveChanges();


            return View("cast");
           

        }

    }
}

MovieShop.MVC/Controllers/CrewController.cs
using MovieShop.MVC.ViewModel;
using MovieShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{

    [RoutePrefix("crew")]
    public class CrewController : Controller
    {
        private CrewService _crewService;

        public CrewController()
        {
            _crewService = new CrewService();
        }

        // GET: Crew
        [HttpGet]
        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            var crew = _crewService.GetCrewDetails(id);
            var crewDetailsViewModel = new CrewDetailsViewModel();
            crewDetailsViewModel.Id = crew.Id;
            crewDetailsViewModel.Name = crew.Name;
            crewDetailsViewModel.Movies = new List<MovieDetailsViewModel>();

            foreach (var movie in crew.MovieCrews)
            {
                crewDetailsViewModel.Movies.Add(new MovieDetailsViewModel() { Id = movie.MovieId, Title = movie.Movie.Title });

            }
            return View(crewDetailsViewModel);

        }
        [HttpGet]
        [Route("Index")]//localhost/Crew/Index
        public ActionResult Index()
        {
            var crews = _crewService.GetAllCrews();
            return View(crews);
        }
      

    }

}

MovieShop.MVC/Controllers/GenreController.cs
using MovieShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class GenreController : Controller
    {
        private readonly GenreService _genreService;

        public GenreController()
        {
            _genreService = new GenreService();
        }

        // GET: Genre


        //public ActionResult Index()
        //{
        //    return View();

        //}



        public PartialViewResult Index()
        {
            return PartialView("GenreView", _genreService.GetAllGenres().OrderBy(g => g.Name).ToList());
        }

    }
}

MovieShop.MVC/Controllers/HomeController.cs
using MovieShop.Entities;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        private static Logger logger = LogManager.GetCurrentClassLogger();
        public void Index1()
        {
            logger.Debug("Hello from Home Controller...");
        }


    }
}

MovieShop.MVC/Controllers/MoviesController.cs
using MovieShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class MoviesController : Controller
    {
        private MovieService _movieService;
        public MoviesController()
        {
            _movieService = new MovieService();
        }
        // GET: Movies
        public ActionResult Index()
        {

            var movies = _movieService.GetTopGrossingMovies();
            return View(movies);
        }
    }
}

MovieShop.MVC/Views/Cast/Create.cshtml
@model MovieShop.Entities.Cast

@{ 
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create","Cast",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cast</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @*HTML Helper*@
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TmdbUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TmdbUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TmdbUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*{ @class : need @ bc class is a key word*@

MovieShop.MVC/Views/Cast/Details.cshtml
@model MovieShop.MVC.ViewModel.CastDetailsViewModel


@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cast</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)

        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TmdbUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TmdbUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePath)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.ProfilePath)*@
            <img src="@Model.ProfilePath" alt="Selfie">


        </dd>

    </dl>

</div>

<div>
    <table class="table">
        <tr>
            <td>Id</td>
            <td>Title</td>
        </tr>
        <tbody>
            @foreach (var movie in Model.Movies)
            {
            <tr>
                <td>@movie.Id</td>
                @*<td>@movie.Title</td>*@
                <td>@Html.ActionLink(movie.Title, "Edit", new { id = Model.Id })</td>
            </tr>
            }
        </tbody>      
    </table>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MovieShop.MVC/Views/Cast/Index.cshtml
@model IEnumerable<MovieShop.Entities.Cast>

@{
    ViewBag.Title = "Index";
}

<h2>
    Index
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TmdbUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfilePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Name)*@
            @Html.ActionLink(item.Name, "Details", new { id = item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.TmdbUrl)*@
            @*<a href="@Url.Action(item.TmdbUrl, "TmdbUrl")" class="fas fa-external-link-alt"></a>*@
            @*@Html.ActionLink("logo", "Details", "", new { @class = "fas fa-external-link-alt" })*@
            <a href="@item.TmdbUrl">
                <img alt="Qries" src="https://img.icons8.com/dusk/64/000000/external-link.png"
                     width="70" height="70">
            </a>
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.ProfilePath)*@
            <img src="@item.ProfilePath" alt="Selfie" height="100" width="100">
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MovieShop.MVC/Views/Crew/Details.cshtml
@model MovieShop.MVC.ViewModel.CrewDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Crew Details</h2>

<div>
    <h4>Cast</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

</div>


<div>
    <table class="table">
        <tr>
            <td>Id</td>
            <td>Title</td>
            <td>PosterURL</td>
            <td>Revenue</td>
            <td>ImdbUrl</td>

        </tr>
        <tbody>
            @foreach (var movie in Model.Movies)
            {
            <tr>
                <td>@movie.Id</td>
                <td>@movie.Title</td>
                <td>@movie.PosterUrl</td>
                <td>@movie.Revenue</td>
                <td>@movie.ImdbUrl</td>
            </tr>
            }
        </tbody>
    </table>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MovieShop.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MovieShop.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieShop.MVC/Views/Home/Index.cshtml
@model IEnumerable<MovieShop.Entities.Movie>
@{
    ViewBag.Title = "Home Page";
}

<h1>Home Page</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        @{
            var first = true;
        }
        @foreach (var movie in Model)
        {
            <div class="carousel-item @(first ? Html.Raw("active") : Html.Raw(""))">
                <img class="d-block w-100" src="@movie.BackdropUrl" alt="@movie.Title">
            </div>
            first = false;
        }
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

MovieShop.MVC/Views/Movies/Details.cshtml
@model MovieShop.MVC.ViewModel.CrewDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Movies Details</h2>
<h3>Cast Info:</h3>

<div>
    <table class="table">
        <tr>
            <td>Id</td>
            <td>Title</td>
            <td>PosterURL</td>
            <td>Revenue</td>
            <td>ImdbUrl</td>

        </tr>
    </table>
</div>

<div>
    <table class="table">
        <tr>
            <td>Id</td>
            <td>Title</td>
        </tr>
        <tbody>
            @foreach (var movie in Model.Movies)
            {
                <tr>
                    <td>@movie.Id</td>
                    @*<td>@movie.Title</td>*@
                    <td>@Html.ActionLink(movie.Title, "Edit", new { id = Model.Id })</td>
                </tr>
            }
        </tbody>
    </table>
</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MovieShop.MVC/Views/Movies/Index.cshtml
@model List<MovieShop.Entities.Movie>
@{
    ViewBag.Title = "Index";
}

<h2>Top Grossing Movies</h2>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Revenue</th>
            <th>Released Date</th>
        </tr>
        @foreach (var movie in Model)
        {
    <tr>
        <td>
            @movie.Id
        </td>
        <td>
            @movie.Title
        </td>
        <td>
            @movie.Revenue
        </td>
        <td>
            @movie.ReleaseDate
        </td>
    </tr>
        }
    </thead>
</table>

MovieShop.MVC/Views/Shared/DetailsPartial.cshtml
@model IEnumerable<MovieShop.Entities.MovieCast>

<p>
    This is a Cast Id Movie
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MovieId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Movie)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @*@Html.DisplayFor(modelItem => item.Id)*@
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Name)*@
                @*@Html.ActionLink(item.Name, "Details", new { id = item.Id })*@
            </td>
            <td>
            </td>
        </tr>
    }

</table>

MovieShop.MVC/Views/Shared/GenreView.cshtml
@model IEnumerable<MovieShop.Entities.Genre>

@foreach (var genre in Model)
{
    @Html.ActionLink(genre.Name, "Genre", "Movie", new {genreID = genre.ID}, new { @class = "dropdown-item" })

}

MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top ">
        @Html.ActionLink("Movie Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })

                </li>

                <li class="nav-item active">
                    @Html.ActionLink("Movies", "Index", "Movies", null, new { @class = "nav-link" })

                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Movies
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Top Movies", "Genre", "Movies", "", new { @class = "dropdown-item" })
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Genres
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @{ Html.RenderAction("Index", "Genre"); }
                    </div>
                </li>


                <li class="nav-item active">
                    @Html.ActionLink("SignIn", "User", "SignIn", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("SignUp", "User", "SignUp", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
    </nav>


    <div class="container-fluid mt-5 pt-4">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Movie Shop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>